version: '3.9'

services:
  nuxt:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: template-nuxt-app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NODE_ENV
      - BASE_URL
      - AUTH_SECRET
      - DATABASE_URL
    networks:
      - app-network

  postgres:
    image: postgres:14
    container_name: template-postgres
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: